<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.10.12 on linux)" generated="20240508 13:26:43.857" rpa="false">
<suite id="s1" name="Test" source="/home/oma_b/code-X/appium_python/robot/test.robot">
<test id="s1-t1" name="Open_Application">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>http://localhost:4723/wd/hub</arg>
<arg>platformName=Android</arg>
<arg>deviceName=emulator-5554</arg>
<arg>appPackage=chat21.android.demo</arg>
<arg>appActivity=chat21.android.demo.SplashActivity</arg>
<arg>automationName=Uiautomator2</arg>
<arg>timeout=60</arg>
</arguments>
<msg timestamp="20240508 13:26:43.987" level="TRACE">Arguments: [ 'http://localhost:4723/wd/hub' | platformName='Android' | deviceName='emulator-5554' | appPackage='chat21.android.demo' | appActivity='chat21.android.demo.SplashActivity' | automationName='Uiautomator2' | timeout=60 ]</msg>
<msg timestamp="20240508 13:26:43.990" level="DEBUG">POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:deviceName": "emulator-5554", "appium:appPackage": "chat21.android.demo", "appium:appActivity": "chat21.android.demo.SplashActivity", "appium:automationName": "Uiautomator2", "appium:timeout": 60}]}, "desiredCapabilities": {"platformName": "Android", "deviceName": "emulator-5554", "appPackage": "chat21.android.demo", "appActivity": "chat21.android.demo.SplashActivity", "automationName": "Uiautomator2", "timeout": 60}}</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20240508 13:26:43.990" level="TRACE">Arguments: [  ]</msg>
<msg timestamp="20240508 13:26:43.991" level="FAIL">No application is open</msg>
<msg timestamp="20240508 13:26:43.991" level="DEBUG">Traceback (most recent call last):
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/keywordgroup.py", line 21, in _run_on_failure_decorator
    raise err
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/keywordgroup.py", line 16, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/_screenshot.py", line 31, in capture_page_screenshot
    if hasattr(self._current_application(), 'get_screenshot_as_file'):
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/_applicationmanagement.py", line 350, in _current_application
    raise RuntimeError('No application is open')</msg>
<status status="FAIL" starttime="20240508 13:26:43.990" endtime="20240508 13:26:43.991"></status>
</kw>
<msg timestamp="20240508 13:26:43.992" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20240508 13:26:43.993" level="FAIL">ValueError: Timeout value connect was &lt;object object at 0x730c56388c10&gt;, but it must be an int, float or None.</msg>
<msg timestamp="20240508 13:26:43.994" level="DEBUG">Traceback (most recent call last):
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/keywordgroup.py", line 21, in _run_on_failure_decorator
    raise err
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/keywordgroup.py", line 16, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/AppiumLibrary/keywords/_applicationmanagement.py", line 53, in open_application
    application = webdriver.Remote(str(remote_url), desired_caps)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py", line 151, in __init__
    super().__init__(
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 433, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 304, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 329, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 352, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 266, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 196, in __init__
    timeout = Timeout.from_float(timeout)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/home/oma_b/code-X/appium_python/robot/.venv/lib/python3.10/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(</msg>
<status status="FAIL" starttime="20240508 13:26:43.987" endtime="20240508 13:26:43.994"></status>
</kw>
<status status="FAIL" starttime="20240508 13:26:43.987" endtime="20240508 13:26:43.994" critical="yes">ValueError: Timeout value connect was &lt;object object at 0x730c56388c10&gt;, but it must be an int, float or None.</status>
</test>
<status status="FAIL" starttime="20240508 13:26:43.858" endtime="20240508 13:26:43.994"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240508 13:26:43.992" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
